AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/console'
    - 'bin/setup'
    - 'pkg/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
